name: HubSpot deployment

on:
  push:
    branches:
      - main
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install HubSpot CLI Action
        uses: HubSpot/hubspot-project-actions/install-hubspot-cli@v1.0.0

      - name: HubSpot Project Upload
        uses: HubSpot/hubspot-project-actions/project-upload@v1.0.0
        with:
          project_dir: "./app"
        env:
          # This connects HubSpot's action inputs directly to your existing secrets!
          HUBSPOT_ACCOUNT_ID: ${{ secrets.HS_ACCOUNT_ID }}
          HUBSPOT_PERSONAL_ACCESS_KEY: ${{ secrets.HS_PORTAL_AUTH_TOKEN }}