name: CICD

on:
  push:
    branches:
      - main


concurrency:
  group: hubspot-deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
    changes:
        runs-on: ubuntu-latest
        outputs:
            hubspot-crm: ${{ steps.filter.outputs.hubspot-crm }}
            hubspot-functions: ${{ steps.filter.outputs.hubspot-functions }}

        steps:
          - uses: actions/checkout@v4
          - uses: dorny/paths-filter@v3
            id: filter
            with:
              filters: |
                hubspot-crm:
                  - 'app/**'
                hubspot-functions:
                  - 'hubspot/**'
            
    hubspot-crm:
        needs: changes
        if: needs.changes.outputs.hubspot-crm == 'true'
        permissions: 
            id-token: write
            contents: read
        uses: './.github/workflows/hubspot-crm.yml'
        with:
            working-directory: hubspot
        secrets: inherit  

    hubspot-functions:
        needs: changes
        if: needs.changes.outputs.hubspot-functions == 'true'
        permissions:
            id-token: write
            contents: read
        uses: './.github/workflows/hubspot-functions.yml'
        with:
            working-directory: hubspot
        secrets: inherit 