name: HubSpot deployment

on:
  push:
    branches:
      - main

jobs:
  hubspot-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install HubSpot CLI
      run: npm install -g @hubspot/cli

    - name: Create HubSpot Config File
      run: |
        mkdir -p .config/hubspot
        echo '{
          "defaultPortal": "production",
          "portals": [
            {
              "name": "production",
              "portalId": ${{ secrets.HS_ACCOUNT_ID }},
              "token": "${{ secrets.HS_PORTAL_AUTH_TOKEN }}"
            }
          ]
        }' > .config/hubspot/hubspot.config.json

    - name: Upload Project Changes
      env:
        HS_CONFIG_FILE: ${{ github.workspace }}/app/.config/hubspot/hubspot.config.json
      run: hs project upload --account=production